#!/usr/bin/env python

import click
import bbc_feeds as feeds

@click.group()
def bbc():
    'Get BBC feeds of several categories'

@bbc.command()
@click.argument('category', required=True)
@click.option('--limit', type=click.INT, required=False, default=False, help='Limit of entries')
@click.option('--edition', type=click.Choice(['us', 'uk', 'int'], case_sensitive=False), required=False, default='int', help='Edition to use for top stories')
def news(category, edition, limit):
    if category == 'all':
        click.echo(feeds.news().all(limit=limit))
    if category == 'world':
        click.echo(feeds.news().world(limit=limit))
    if category == 'uk':
        click.echo(feeds.news().uk(limit=limit))
    if category == 'north_america':
        click.echo(feeds.news().north_america(limit=limit))
    if category == 'entertainment':
        click.echo(feeds.news().entertainment(limit=limit))
    if category == 'business':
        click.echo(feeds.news().business(limit=limit))
    if category == 'tech':
        click.echo(feeds.news().tech(limit=limit))
    if category == 'top_stories':
        click.echo(feeds.news().top_stories(edition=edition, limit=limit))

@bbc.command()
@click.argument('category', required=True)
@click.option('--limit', type=click.INT, required=False, default=False, help='Limit of entries')
def sports(category, limit):
    if category == 'all':
        click.echo(feeds.sports().all(limit=limit))
    if category == 'cricket':
        click.echo(feeds.sports().cricket(limit=limit))
    if category == 'soccer':
        click.echo(feeds.sports().soccer(limit=limit))
    if category == 'tennis':
        click.echo(feeds.sports().tennis(limit=limit))
    if category == 'athletics':
        click.echo(feeds.sports().athletics(limit=limit))
    if category == 'golf':
        click.echo(feeds.sports().golf(limit=limit))
    if category == 'boxing':
        click.echo(feeds.sports().boxing(limit=limit))
    if category == 'swimming':
        click.echo(feeds.sports().swimming(limit=limit))
    if category == 'cycling':
        click.echo(feeds.sports().cycling(limit=limit))
    if category == 'formula1':
        click.echo(feeds.sports().formula1(limit=limit))

@bbc.command()
@click.argument('city_ID', required=True, type=click.INT)
@click.option('--limit', type=click.INT, required=False, default=False, help='Limit of entries')
def weather(city_id, limit):
    click.echo(feeds.weather().forecast(city_id))

bbc()